name: Docker Image CI

on:
  push:
    branches: none # [ "master" ]
  pull_request:
    branches: none # [ "master" ]

     # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Run code analysis
      run: dotnet tool install --global dotnet-sonarscanner
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


    - name: Analyze code
      run: dotnet sonarscanner begin /k:"dotnet-todo" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /o:sonar.organization="jandreja" sonar.host.url=https://sonarcloud.io
    
    - name: Build the Docker image
      run: docker build . --file ./src/Dockerfile --tag todo_container:${{ github.run_number }}
