name: Docker Image CI

on:
  push:
    branches: none # [ "master" ]
  pull_request:
    branches: none # [ "master" ]

     # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4


    - name: Analyze code
      run: dotnet sonarscanner begin /k:"JAndreja_dotnet-todo" /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
    
    - name: Build the Docker image
      run: docker build . --file ./src/Dockerfile --tag todo_container:${{ github.run_number }}
