name: Docker Image CI

on:
  push:
    branches: none # [ "master" ]
  pull_request:
    branches: none # [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Build the Docker image
      working-directory: src
      run: docker build . --file Dockerfile --tag my-image-name
